# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Axel Grimault
email: axel[.]grimault[at]gmail[.]com
emailbis: axel[.]grimault[at]univ[-]angers[.]fr
description: > # this means to ignore newlines until "baseurl:"
  Maître de Conférences </br>
  IUT Angers-Cholet | Université d'Angers </br>
  Laboratoire LARIS </br>
  4 boulevard Lavoisier, 49016 Angers
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: axelgrimault
github_username:  biblik
linkedin_username: axelgrimault
googlescholar_id: Cu-JqWAAAAAJ
googlescholar_username: axel.grimault
future: true
# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
